name: my_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-VariableFont_wght.ttf
        - asset: assets/fonts/Rubik-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Rubik-SemiBold.ttf
        - asset: assets/fonts/Rubik-Bold.ttf
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-VariableFont_wght.ttf
        - asset: assets/fonts/Jost-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/Jost-SemiBold.ttf
        - asset: assets/fonts/Jost-Bold.ttf
